version: "3.8"

# volumes:
#   keycloak_db_data:


services:
  keycloak-db:
    image: postgres:14.4-alpine
    container_name: keycloak-db
    # volumes:
    #   - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak-service:
    container_name: keycloak-service
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KEYCLOAK_LOGLEVEL=TRACE
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command:
      [
        "start-dev",
        # "--db=postgres",
        # "--db-url=jdbc:postgresql://keycloak-db:5432/keycloak",
      ]
    # command: [ "start", "--optimized" ]
    ports:
      - "8800:8080"
      - "8443:8443"
